# fly.toml app configuration file generated for classifier-zmrrsg on 2026-02-17T18:55:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'classifier-zmrrsg'
primary_region = 'arn'

[build]

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.ports]]
    port = 50051

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"  

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
